- check.go
- cmd/gomtree/main.go
- hierarchy.go
- parse.go
This makes the result set more useful. Also, this fixes a bug for deriving paths of an entry when parsing an mtree file specification.
> Check results

- check.go
- check_test.go
- cmd/gomtree/main.go
Allow for `Check()` to be narrowed to a set of keywords.
> check: keyword filtering the checks

- check.go
Error out if a keyword is not valid. Previous version of Check() just `continue`'d if `kv.Keyword()` was not in `keywords`, and this allowed Check() to pass without any errors regarding the validity of a keyword.
> check: error out on unrecognized keyword

- check.go
Fixes #11. Check() changes its working directory to `root`, which is specified as an argument. Thus, it shouldn't call `os.Lstat` on a file using its absolute path; instead it should open the file
with the relative path to the root.
> check: recognize correct path

- cmd/gomtree/main.go
Resolves #21 . 'type' keyword is a default that should always be evaluated, aligning with upstream mtree.
> main: 'type' keyword should always be evaluated

- check_test.go
- parse.go
Comments were only ignored if the string parsed strictly started with "#". This commit resolves this issue by stripping leading whitespace from the string being examined.
> parse: ignore leading whitespace for comments

- keywords.go
Fixes #7 . golang has constants for the `FileMode` type: `os.ModeSticky`, `os.ModeSetuid`, and `os.ModeSetgid`. Mask `info.Mode()` with the respective constant to check if the bit is set for a particular file (where `info` is the `os.FileInfo()` of the file we are examining).
> keywords: obtain all permission bits

- check.go
- check_test.go
Fixes a pointer aliasing bug. creator.curSet was being set to the address of the variable `e` iterating over the range of Entries, and this caused the underlying value of the Entry it points to to change on each iteration.
> check: creator.curSet pointer aliasing

- README.md
- cmd/gomtree/main.go
The FreeBSD flag `-l` is already used and has differing behavior, so
switch to not conflict
Reported-by: Aleksa Sarai <asarai@suse.de>
> main: change `-l` to `-list-keywords`

- walk.go
When checking if a new set is needed once `curSet != nil`, the new set created is not filtered against the `keywords` argument in `Walk()`. This caused new sets to contain keywords found in `defaultSetKeywords`, but not in `keywords`, which should be the 'limiting' factor for what actually is evaluated when `Walk`ing.
> [bug fix] walk: filter \set keyword correctly

- check.go
- cmd/gomtree/main.go
This adds the following `--output` formats:
* `bsd` (the default and the original version).
* `json` which outputs a JSON encoded version of the struct for easier parsing.
* `path` which just outputs the full path which failed for easier parsing by shell scripts and the like.
> cmd: add alternate formats

- check.go
- check_test.go
- hierarchy.go
- unvis.go
- vis.go
- vis_test.go
- walk.go
Refactored gomtree with the `vis` and `unvis` C functions. Validation manifest should now be in same format with upstream mtree in terms of how filenames are represented.
> vis: refactored code to reflect using vis() to represent file names

- check.go
When using `-result-format=json` flag, just show populated fields.
Before:
```bash
$ gomtree -result-format=json -p ./bin -f ./bin.mtree
{"failures":[{"path":"gomtree","keyword":"size","expected":"2646101","got":"2930231"}],"Missing":null,"Extra":null}
```
After:
```bash
$ gomtree -result-format=json -p ./bin -f ./bin.mtree
{"failures":[{"path":"gomtree","keyword":"size","expected":"2646101","got":"2930231"}]}
```
> check: omitempty rather than `null`

- cmd/gomtree/main.go
When adding keywords with -K, we don't want to duplicate keywords in the keywords slice.
> main: don't dupliate keywords

- cmd/gomtree/main.go
#29 accidentally put the functionality for when gomtree has no arguments inside an unreachable block.
> cmd: gomtree no arguments

- tar.go
When running `gomtree` on a tar archive representing a large filesystem (I mounted a fedora image to `/mnt`), I got:
```
[schung@localhost Desktop] $ sudo `which gomtree` -c -T mount.tar
2016/07/25 20:03:16 open /tmp/ts.payload.682784237: too many open files
[schung@localhost Desktop] $ echo $?
1
```
The temp files in `tar.go` the files were just being `defer`ed on each iteration and not being closed right away after each iteration, which is what we expect. To resolve, just close the files right after `populateTree`.
Now:
```
[schung@localhost Desktop] $ sudo `which gomtree` -c -T mount.tar > mount.mtree
[schung@localhost Desktop] $ echo $?
0
```
> [bug fix] tar: explicitly close files after populateTree

- cmd/gomtree/main.go
- debug.go
- keywords.go
- keywords_linux.go
- xattr/xattr.go
* Fixes `xattr` issue, that caused an ERANGE failure if there we _no_ xattrs on a file.
* add an alias of `xattrs`
Also, this introduces a `-debug` flag to the tool. Where there is an `mtree.Debugf()` function to log to stderr
> fix xattr ERANGE

- cmd/gomtree/main.go
- keywords.go
To support either producing or checking manifests that are compatible
with upstream FreeBSD mtree(8) keywords, this flag will only operate on
upstream keywords. Completely ignoring non-upstream keywords, though
printing out an INFO to stderr for information purposes.
Example:
```bash
INFO: ignoring "xattrs" as it is not an upstream keyword
/set type=file nlink=1 mode=0664 uid=1000 gid=100
. size=4096 type=dir mode=0755 nlink=2 time=1469556206.235575511
[...]
```
> Bsd keywords

- keywords.go
Currently, if you create a manifest with, say 'sha1', and another manifest with 'sha1digest', gomtree will produce different output with regard to the keyword name. I.e, `sha1=[...]` vs. `sha1digest=[...]`.
If we want to use synonyms for keywords, as well as align with upstream mtree output, specifying 'sha1' and 'sha1digest' should impact gomtree functionality in the same way.
> keywords: synonyms of keywords should produce same output

- README.md
- keywords_linux.go
Rather than an arbitrary election of hashing the xattr value with SHA1
to avoid leaking the value. By going with base64 encoding it allows for
the possibility of restoring a directory with the values stored in the
manifest.
> keywords: switch 'xattr' to base64

- cmd/gomtree/main.go
- hierarchy.go
When you specify a validation manifest with the `-f` flag, you can now specify a `-list-used` flag that generates a list of keywords used in that manifest, instead of validating the manifest. This increases a user's control in the workflow of validating a directory or archive.
`gomtree -f <validation manifest> -list-used`
> hierarchy: provide option to list the used keywords in a spec

- keywords.go
Previously, the symlink size reported by a archive/tar header
was 0. This is incorrect, as the size of a symlink should be
the size of its contents, which is just the path to where
the symlink points to. Thus, the size of this file would just
be len(Linkname).
> keywords: return non-zero symlink size

- cmd/gomtree/main.go
Piggybacking on `-result-format`:
```bash
$ tar c .git/ | gomtree -c -T - > git.mtree
$ gomtree -result-format=json -list-used -f ./git.mtree
{
"./git.mtree": [
"type",
"mode",
"uid",
"gid",
"tar_time",
"size"
]
}
$ tar c .git/ | gomtree -c -T - -K sha512digest > git.mtree
$ gomtree -result-format=json -list-used -f ./git.mtree
{
"./git.mtree": [
"type",
"mode",
"uid",
"gid",
"tar_time",
"size",
"sha512digest"
]
}
```
> gomtree: `-list-used` can output JSON

- tar_test.go
right now, Check() doesn't check for missing/extra files. So, for the
sake of this test, we don't want to do this check for extra/missing files
when we validate the validation manifest produced from a tar against
the "." root directory (which would be /testdata).
> tar_test: don't check for extra/missing when validating relative to "."

- cmd/gomtree/main.go
- version.go
In order to have coordinated releases, add an `mtree.Version` variable and a `-version` flag to the cli.
> Add versioning

- keywords.go
- keywords_bsd.go
- keywords_linux.go
BSD file's support "flags". These have some similarity with xattr, but
for specific features, rather than general purpose key/values.
> keywords: don't fail on presence of "flags"

- keywords.go
- keywords_test.go
Previously, the time generation code would inexplicably drop parts of
the nanotime -- potentially causing validation to succeed when it should
fail. This was probably do to a bug in the remainder logic, but instead
we should be using .Nanosecond() anyway.
After changing the time of a file with a test case like this:
// Change the time to something known with nanosec != 0.
chtime := time.Unix(100, 987654321)
if err := os.Chtimes("somefile", chtime, chtime); err != nil {
// panic
}
timeKeywordFunc() would return the wrong value (time=100.000000021).
This fixes the issue and adds a test case.
> keywords: correctly handle time keywords

- keywords.go
- tar.go
- test/cli/0002.sh
symlink(2) is a very dumb syscall, and allows you to put any damn value
you please inside a symlink. In addition, spaces are valid path
characters which causes issues with keyword parsing. So use Vis() and
Unvis() to safely store an encoded version of the path.
This also adds a cli test for this behaviour.
Fixes #84 
> keywords: safely encode symlink keywords

- check.go
- check_test.go
- cmd/gomtree/main.go
- compare.go
- compare_test.go
- entry.go
- keywords.go
- parse.go
- tar_test.go
This patchset implements manifest comparison as a first-class primitive and then refactors all of the other checking and validation code into manifest comparison operations. This ensures consistency of comparisons, less code to maintain as well as providing some extra features to the client that are not available already. It also increases the usefulness of `go-mtree` as a standalone library.
Supersedes #34.
Signed-off-by: Aleksa Sarai asarai@suse.de
> mtree: implement manifest comparisons

- Makefile
- check.go
- check_test.go
- cmd/gomtree/main.go
- compare.go
- compare_test.go
- entry.go
- hierarchy.go
- hierarchy_test.go
- keywordfunc.go
- keywords.go
- keywords_bsd.go
- keywords_linux.go
- keywords_test.go
- parse.go
- tar.go
- tar_test.go
- test/cli/0004.sh
- test/cli/0005.sh
- version.go
- walk.go
There are a few confusing places of whether a `string` is a keyword name or a `keyword=value` pair. So this makes pretty extensive use of the `Keyword` and `KeyVal` types.
Further, in this there is further comparison with the workflow that is expected on validating manifests, like the behavior found in FreeBSD (it's the precedent).
> Keyword overhaul

- tar.go
- walk.go
Since not every keyword applies to every type entry, include a comment
with the keywords the manifest was generated with.
> entries: comment with keyword metadata

- cmd/gomtree/main.go
The BSD format needed a slight tweak to handle mtree.Extra
and mtree.Missing cases.  It currently only handled the 'Modified'
cases and therefore was not showing missing or extra files during
validation.
> cmd/gomtree/main.go: Handle Extra and Missing cases

- Makefile
- test/cli.go
- test/cli/0001.sh
- test/cli/0002.sh
- test/cli/0004.sh
- test/cli/0005.sh
- test/cli/0006.sh
This cleans up the Makefile target, and drops the dependency to point to
the $root path of the repo.
Fixes https://github.com/vbatts/go-mtree/issues/98
Reported-by: Aleksa Sarai <asarai@suse.de>
> cli.test: fail on cli tests

- compare_test.go
This is trying to figure out why the tar logic is not working the same on openbsd. Current output looks like
```
=== RUN   TestTarCompare
--- FAIL: TestTarCompare (0.07s)
compare_test.go:449: FAILURE: diff[0] = {
"type": "modified",
"path": "tmpfile",
"keys": [
{
"type": "modified",
"name": "gid",
"old": "0",
"new": "1000"
}
]
}
compare_test.go:449: FAILURE: diff[1] = {
"type": "modified",
"path": "testdir",
"keys": [
{
"type": "modified",
"name": "gid",
"old": "0",
"new": "1000"
}
]
}
compare_test.go:449: FAILURE: diff[2] = {
"type": "modified",
"path": "testdir/anotherfile",
"keys": [
{
"type": "modified",
"name": "gid",
"old": "0",
"new": "1000"
}
]
}
compare_test.go:456: expected the diff length to be 0, got 3
FAIL
exit status 1
FAIL    github.com/vbatts/go-mtree      0.123s
```
> compare: make the test output more readable

- check.go
- check_test.go
- cmd/gomtree/main.go
- compare_test.go
- creator.go
- fseval.go
- fseval_test.go
- tar_test.go
- walk.go
- walk_test.go
When walking a directory as an unprivileged user, it is possible for
open(2) to fail even though you still technically have the ability to
grant yourself permissions to open the file [specifically if you're the
owner you can change the mode to give yourself permission]. This is
quite dodgy in some respects, so will need to be hidden behind a "trust
me I'm a professional" flag.
Implements: #89.
> walk: implement "unprivileged manifest generation"

- compare.go
Because of how xattr works (it will not be set on all files, but it's
possible for it to be added to a file without changing any other key)
it's necessary that we _always_ compute a diff when we hit an inode that
has xattr keys set.
Fixes #107 
@vbatts: I'm not sure how to add a test that requires `xattrs` being set on files. I could try doing it as a `tar_test` but that feels like an even worse idea.
> compare: always diff "xattr" keys

- cmd/gomtree/main.go
- keywords_linux.go
- test/cli.go
- test/cli/0003.sh
This allows for xattr keywords to include spaces and other such options
(which is perfectly valid according to the definition of Lsetxattr --
any character except '\x00' is fair game).
Fixes #109
> keywords: encode xattr.* keywords with Vis

- test/cli/0003.sh
this early check was not valid as it required a value before it would
attempt to set the xattr
> cli.test: setting xattr requires a value

- cmd/gomtree/main.go
- test/cli/0008.sh
like `gomtree -c -p /tmp/dir1 -K sha1 | gomtree -p /tmp/dir2`
> gomtree: allow manifest to be provided on stdin

- unvis_go.go
- unvis_go_test.go
Because the original code for vis() was ported to Go using the []byte{}
notion, this causes issues for multi-rune bytes (which were not
correctly treated -- and caused loss of information).
Fix this by dealing with []rune instead, which better conveys the
concept at hand. In addition, add tests to ensure that this does not
happen again.
Though, we _really_ should move this code into a library which has a
better test suite -- and the parser itself should be reimplemented to be
less ... 80s.
Fixes: #118
> unvis_go: leave unicode unchanged with Unvis()

- test/cli/0009.sh
This wraps up the govis changes. While umoci has much more hardcore
tests for unicode, this is done to ensure that go-mtree won't break
before its vendored into umoci.
> test: cli: add unicode verification test

- keywords_linux_test.go
- tar_test.go
- xattr/xattr_test.go
Some build systems may not permit writing to . during build, so allow
that path to be overridden with an environment variable.
> test: Allow using an environment variable to override the test dir

- keywordfunc.go
- keywords.go
Fixes: #127
Reported-by: Lennart Poettering lennart@poettering.net
> keyworrd: fix block device value for `type=`

- keywordfunc.go
- keywordfuncs_bsd.go
- keywordfuncs_linux.go
- keywordfuncs_unsupported.go
- lookup_new.go
- lookup_old.go
Fixes: #128
Reported-by: Lennart Poettering <lennart@poettering.net>
> keyword: add missing `gname` keyword functions

- fseval_test.go
while testing on osx, it seems that it doesn't support nanoseconds so it
fails this check because the mockFsEval returns the nsec precision, but
the actual expected results is:
"old": "1337888911.288518233"
"new": "1337888911.000000000"
Ideally there will be a way to detect when the fs supports nsecs
> fseval: not nanosecond for mock test

- compare.go
- keywords.go
- keywords_test.go
KeyVal specific functions can be a part of the struct.
Also add tests and fix the NewValue functions for suffixes
> keyval: cleaner struct functions

- cmd/gomtree/main.go
- entry.go
- stat_unix.go
- stat_windows.go
- test/cli/0009.sh
- update.go
- update_test.go
- updatefuncs.go
- updatefuncs_linux.go
- updatefuncs_unsupported.go
Fixes #16
In attempt to close https://github.com/vbatts/go-mtree/issues/16 I've
uncovered that the update was missing a function for symlink.
Additionally the update was not even opperating on the correct directory
hierarchy.
I've uncovered that os.Chtimes follows the symlink, and presumably only
Linux has an obscure way to set the mtime/atime on a symlink itself. So
I've made a custom lchtimes().
Also Mode follows through the symlink, and symlinks only ever have a
mode of 0777, so don't set them.
Lastly, directories need to have their mtime/atime set in a reverse
order after all other updates have been done. This is going to require
something like a `container/heap` to be unwound.
Also, each updateFunc will _only_ perform the update if it is needed. Much less
invasive this way. …
> *: update `-u` behavior

- compare.go
- hierarchy.go
- hierarchy_test.go
During the rework of how xattr fields are handled, the comparison code
was not correctly updated. As a result, changes to xattrs would not be
detected in any form. This was detected in the umoci integration suite.
Fixes #140 
Fixes: ed464af779f0 ("*: xattr can Update()")
> compare: correctly use .Prefix() during comparisons

- .travis.yml
- compare.go
This allows people to create synthetic InodeDeltas, which is something
that umoci would like to be able to do in order to nicely create 'umoci
insert' layers.
> compare: allow nil newDh and oldDh

- compare.go
- entry.go
The core issue comes about when you consider a trivial example of a path
like "./README". This path is lexically equivalent within mtree to
"README", but a simple string comparison will yield the wrong result.
Instead you need to lexically clean the path first (filepath.Clean isn't
enough here -- you need to prepend a "/" and then do filepath.Clean).
In gomtree we generate spec files in the same style of FreeBSD's
mtree(8), so you would be very hard-pressed to find an example of such
an inconsistency. However casync's mtree implementation does not
generate leading "./" for root paths which results in "missing" entries.
The implementation of CleanPath was written by me for umoci originally,
then later I copied it to runc for other uses, and now I've copied it
here. Since I'm the sole …
> entry: rework e.Path() handling for casync-mtree

- compare.go
I have a use case where I'd like to know the files that are the same in the
tree, as well as the differences.
I could do this with a separate walk and excluding the paths that were
different, but since mtree is already doing all of this for me, it makes
sense to include it here. I've added a new function so that the behavior
stays the same for existing users of Compare(), since I assume mostly this
will be slower given that most files stay the same. I'd be happy to merge
it into one, though.
Signed-off-by: Tycho Andersen <tycho@tycho.ws>
> compare: add CompareSame()

- cmd/gomtree/main.go
- test/cli/0010.sh
Fixes: #159
```shell
vbatts@fogel:~/src/github.com/vbatts/go-mtree$ ./gomtree -c -f foo
vbatts@fogel:~/src/github.com/vbatts/go-mtree$ ./gomtree -c -f bar -K sha256
vbatts@fogel:~/src/github.com/vbatts/go-mtree$ ./gomtree -f foo -f bar
"foo": unexpected path
".": keyword "time": expected 1649109728.228935367; got 1649109734.412959677
FATA[0000] manifest validation failed
vbatts@fogel:~/src/github.com/vbatts/go-mtree$ echo $?
1
```
> Compare two files

- test/cli/0011.sh
- walk.go
> walk: directory is expected to be walked. A file is not.

- Makefile
> Makefile: only make a single SUMS file, including sha1 and sha512

- parse.go
As per the spec[1], Full entries must not affect the current
directory. Handling this incorrectly caused us issues with certain
manifests (ones with mixed Relative and Full entries).
This is a partial fix for the issues with verifying casync-mtree's
output but there are a few other issues to iron out (including one
within casync).
The spec[1] doesn't mention anything about cleaning paths, but it does
explicitly refer to the path containing a "/". Cleaning the path before
checking if the entry is a FullType would result in the simplest way of
forcing directories to be FullTypes (appending a "/" to the pathname of
any directory) not working with go-mtree.
[1]: https://man.netbsd.org/mtree.5
Partial fix of #146 
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
> parse: improve FullType handling

- .github/workflows/validation.yml
- Makefile
- check_test.go
- cmd/gomtree/cmd/validate.go
- compare_test.go
- fseval_test.go
- keywordfunc.go
- keywords_linux_test.go
- mtree_test.go
- tar.go
- tar_test.go
- test/cli-test/main.go
- update.go
- update_linux_test.go
- update_test.go
- walk_test.go
- xattr/xattr_test.go
- xattr/xattr_unsupported_test.go
Also switch away from deprecated ioutil
> *.go: update to golangci-lint, and fix everything
