check_test.go
cksum_test.go
hierarchy.go
mtree_test.go
walk_test.go

Not full coverage, but enough to start with

Tests pass

---

.travis.yml
hierarchy.go
parse.go
walk.go
xattr/xattr_test.go

travis: add travis checks

---

.travis.yml

travis: go1.5 and go1.6 have vet builtin

---

walk.go

walk: when directory is root, use "."

---

check_test.go
keywords.go

Fix time comparison

---

cmd/gomtree/main.go

gomtree: ensure validating a populated hierarchy

---

walk.go

Aligning with upstream mtree output, produce metadata signature when printing a file spec.

Create and insert metadata Entry's

---

README.md

Creating PR for #47 so we can all discuss what new details should be added. I started with adding some details about `gomtree -T`

readme: update details about go-mtree in readme

---

tar.go

@stephen679 perhaps like this is clearer?

tar: more clear `if` predicate

---

cmd/gomtree/main.go

gomtree: allow tar from stdin

---

check_test.go

test: cleanup testdir after testing

---

tar.go

minor clean-up of some comments that seem unnecessary and code that is not used
in tar functionality to help readability
Signed-off-by: Stephen Chung <spchung@andrew.cmu.edu>

tar: remove completed TODO's and dead code

---

keywords_linux.go
keywords_linux_test.go

keywords: fix xattrs for broken symlinks

---

.travis.yml

travis: update versions of golang

---

keywords_bsd.go
keywords_linux.go
keywords_unsupported.go

keywords: BSD compat for a few keywords

---

xattr/xattr_unsupported_test.go

xattr: tests for non-linux

---

README.md

README: add info on running the tests

---

test/cli/0007.sh

cli.test: add case from #90

---

.travis.yml
Makefile

make: add a specific target for tags

---

xattr/xattr_unsupported.go

xattr: the unsupported features weren't linted

---

.travis.yml
Makefile
keywords_unsupported.go

make: build for several platfom/arches

---

test/cli.go
test/cli/0001.sh
test/cli/0002.sh
test/cli/0003.sh
test/cli/0004.sh
test/cli/0005.sh
test/cli/0006.sh
test/cli/0007.sh

cli.test: passthrough and use TMPDIR

---

releases.md

release: add some steps to remember

---

check_test.go

check: test times weren't different enough

---

update.go
updatefuncs.go
updatefuncs_linux.go
updatefuncs_unsupported.go

updatefunc: simplify the function signature

---

pkg/govis/govis.go

govis: comment for lint

---

keywordfunc.go
keywords.go

Reference: https://github.com/systemd/casync/issues/101#issuecomment-340019721

keyword: include sha-2 512/256

---

check.go
tar_test.go

check: remove unused TarCheck(), for Compare()

---

compare.go

Heh, copypasta error. Amazing I'm the first person who noticed this :)
Signed-off-by: Tycho Andersen <tycho@tycho.ws>

compare: return the right delta

---

README.md

README: github workflow badge

---

keywordfuncs_bsd.go
keywordfuncs_unsupported.go
lchtimes_unix.go
lchtimes_unsupported.go
stat_unix.go
stat_windows.go
updatefuncs_linux.go
updatefuncs_unsupported.go
xattr/xattr_test.go
xattr/xattr_unsupported.go
xattr/xattr_unsupported_test.go

*.go: updated go:build added via gofmt

---

cmd/gomtree/main.go

main: add description output
